name: Workflow name

on: [push]

jobs:
  run-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: echo "Deploy Workflow"
      - name: Echo current date
        run: echo $(date +%s) + $(date)
      - name: Echo secrets
        run: echo "Password:" ${{ secrets.SQL_PASSWORD }} "***"